### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by gldraphael** [gldraphael/clippy#1]
- [x] GitHub action to build and push a docker image to GitHub packages.
- [x] Put together a helm chart.
- [x] GitHub action to build and push a helm OCI artifact to GitHub packages.
